version: '3.0'

services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=application_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5655:5432"
    expose:
      - "5655"
