version: '3.0'

services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sport-booking-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5655:5432"
    expose:
      - "5655"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8000:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: "./"
    environment:
      - POSTGRES_HOST=postgres
    volumes:
      - /app/node_modules
      - /app/prisma
      - ./:/app
    env_file:
      - ./.development.env
    restart: always
    depends_on:
      - postgres
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ../client/.env
    build:
      dockerfile: Dockerfile.dev
      context: ../client
    volumes:
      - /app/node_modules
      - ../client:/app
  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    env_file:
      - ./prisma/.env
    environment:
      - POSTGRES_URL=postgresql://postgres:postgres@postgres:5432/sport-booking-db
    depends_on:
      - postgres
      - api
    ports:
      - '5555:5555'
    expose:
      - '5555'